### ISSUE TITLE
Does not support variables

### ISSUE THREAD

**Issue by kaisellgren** [postcss/postcss-color-hwb#10]
It looks like variables are not supported:

```css
a {
  --base-hue: 240;
  --whiteness: 60%;
  --darkness: 25%;
  color: hwb(var(--base-hue), var(--whiteness), var(--darkness));
}
```

The above code produces:

```Unable to parse color from string: hwb(var(--base-hue), var(--whiteness), var(--darkness))```
