### ISSUE TITLE
Support  the <named-hue>

### ISSUE THREAD

**Issue by yisibl** [postcss/postcss-color-hwb#2]
http://dev.w3.org/csswg/css-color/?c=M%3BO%3DD#simple-hues

Like this: 

``` css
.foo {
  color: hwb(reddish(50%) purple, 30%, 90%)')
}
```
